---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg 
  namespace: cnpg 
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: cloudnative-pg 
      version: '0.24.0'
      sourceRef:
        kind: HelmRepository
        name: cnpg
      interval: 5m
  releaseName: cnpg 
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 1
