---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets 
  namespace: external-secret-operator
spec:
  interval: 10m
  timeout: 5m
  chart:
    spec:
      chart: external-secrets
      version: '0.18.0'
      sourceRef:
        kind: HelmRepository
        name: external-secrets-operator
      interval: 5m
  releaseName: external-secrets-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 2
